name: Build VTK from source

on:
  workflow_dispatch

env:
  PYTHONUTF8: 1
  VTK: 9.3.1
  VTK_MAJOR: 9.3

jobs:
  build:
    name: Build with wrapper for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # os: [ 'ubuntu-20.04', 'macos-13', 'macos-14', 'windows-2019' ]
        os: [ 'windows-2019' ]
        python-version: [ '3.13' ]
        include:
          # - os: "macos-13"
          #   sed_i: "sed -i '.bak'"
          #   shells: "bash"
          # - os: "macos-14"
          #   sed_i: "sed -i '.bak'"
          #   shells: "bash"
          # - os: "ubuntu-20.04"
          #   sed_i: "sed -i"
          #   shells: "bash"
          - os: "windows-2019"
            sed_i: "sed -i"
            shells: "bash cmd.exe"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Get number of CPUs
        shell: bash -l {0}
        id: cpu-count
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            cpu_count=$(sysctl -n hw.logicalcpu)
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            cpu_count=$(nproc)
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            cpu_count=$NUMBER_OF_PROCESSORS
          else
            cpu_count=1
          fi
          echo "cpu_count=$cpu_count" >> $GITHUB_OUTPUT

          echo "=> Using $cpu_count CPUs"

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build-vtk
          init-shell: ${{ matrix.shells }}
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Setup Python Env
        shell: bash -l {0}
        run: |
          micromamba activate build-vtk
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel build setuptools
          python -m pip freeze
          
      # - name: Setup Windows build environment (MSVC)
      #   if: runner.os == 'Windows'
      #   uses: ilammy/msvc-dev-cmd@v1
        
      - name: Ubuntu Deps
        shell: bash -l {0}
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y build-essential cmake mesa-common-dev mesa-utils freeglut3-dev python3-dev python3-venv git-core ninja-build cmake wget libglvnd0 libglvnd-dev
      
      - name: MacOS Deps # 13 and 14
        shell: bash -l {0}
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install ninja

      - name: Load VTK sources
        shell: bash -l {0}
        run: |
          curl -L -O https://vtk.org/files/release/${{ env.VTK_MAJOR }}/VTK-${{ env.VTK }}.tar.gz
          tar -zxf VTK-${{ env.VTK }}.tar.gz
          
          cd VTK-${{ env.VTK }}
          mkdir build

          patch -p1 < ../patches/vtk-${{ env.VTK }}/9987_try_except_python_import.patch
          patch -p1 < ../patches/vtk-${{ env.VTK }}/11486.patch

          if [[ $RUNNER_OS == "Windows" ]]; then
            patch -p1 < ../patches/vtk-${{ env.VTK }}/fix-threads-windows.patch
          fi

      - name: Build Linux python libraries from Scratch
        shell: bash -l {0}
        if: runner.os == 'Linux'
        run: |
          micromamba activate build-vtk

          cd VTK-${{ env.VTK }}/build
          cmake -GNinja \
                -DVTK_WHEEL_BUILD=ON -DVTK_WRAP_PYTHON=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DVTK_CUSTOM_LIBRARY_SUFFIX="" -DVTK_VERSION_SUFFIX="" \
                -DCMAKE_POLICY_DEFAULT_CMP0174=NEW -DCMAKE_POLICY_DEFAULT_CMP0177=NEW \
                ..

          ninja -j ${{ steps.cpu-count.outputs.cpu_count }}

      - name: Build macOS python libraries from Scratch
        shell: bash -l {0}
        if: runner.os == 'macOS'
        run: |
          micromamba activate build-vtk

          cd VTK-${{ env.VTK }}/build
          env "MACOSX_DEPLOYMENT_TARGET=11.1" cmake -GNinja \
                -DVTK_WHEEL_BUILD=ON -DVTK_WRAP_PYTHON=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DVTK_CUSTOM_LIBRARY_SUFFIX="" -DVTK_VERSION_SUFFIX="" \
                -DCMAKE_POLICY_DEFAULT_CMP0174=NEW -DCMAKE_POLICY_DEFAULT_CMP0177=NEW \
                ..

          ninja -j ${{ steps.cpu-count.outputs.cpu_count }}

      - name: Build Windows python libraries from Scratch
        shell: cmd
        if: runner.os == 'Windows'
        run: |
          call C:\Users\runneradmin\micromamba\condabin\micromamba.bat activate build-vtk 
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          cd VTK-${{ env.VTK }}\build          
          cmake -GNinja \
                -DVTK_WHEEL_BUILD=ON -DVTK_WRAP_PYTHON=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DVTK_CUSTOM_LIBRARY_SUFFIX="" -DVTK_VERSION_SUFFIX="" \
                -DCMAKE_POLICY_DEFAULT_CMP0174=NEW -DCMAKE_POLICY_DEFAULT_CMP0177=NEW \
                ..

          ninja -j ${{ steps.cpu-count.outputs.cpu_count }}

      - name: Build wheel
        shell: bash -l {0}
        run: |
          micromamba activate build-vtk

          cd VTK-${{ env.VTK }}/build
          ${{ matrix.sed_i }} "s/dist_name = 'vtk'/dist_name = 'cadquery_vtk'/" dist\*.whl
          python -m build -n -w

      - name: Test wheel
        shell: bash -l {0}
        run: |
          micromamba create -n test python=${{ matrix.python-version }} -y
          micromamba activate build-vtk

          pip install VTK-*/build/dist/*.whl
          python -c "import vtk;print('vtk imported successfully')"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cadquery-vtk-${{ matrix.os }}-cp${{ matrix.python-version }}
          path: VTK*/build/dist/*.whl