name: Compiler Tests

on: workflow_dispatch

jobs:
  build:
    name: Compiler Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-13", "macos-14"]
        python-version: ["3.13"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: cadquery-vtk-${{ matrix.os }}-cp${{ matrix.python-version }}
          run-id: 12550588784

      - name: Install wheel
        run: | 
          ls -l

