name: Matrix Tests

on: workflow_dispatch

jobs:
  build:
    name: Build with wrapper for Python ${{ matrix.python-version }} on ${{ matrix.os }} with VTK ${{ matrix.use-vtk }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-13", "macos-14", "windows-2019"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        use-vtk: ["OFF"]
        include:
          - use-vtk: "ON"
            python-version: "3.10"
          - use-vtk: "ON"
            python-version: "3.11"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Debug
        run: |
          echo "os: ${{ matrix.os }}"
          echo "python-version: ${{ matrix.python-version }}"
          echo "use-vtk: ${{ matrix.use-vtk }}" 