name: Test nlopt and casadi

on: workflow_dispatch

jobs:
  build:
    name: Test nlopt and casadi ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['windows-2019']
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} via micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          log-level: debug
          init-shell: bash cmd.exe
          cache-downloads: true

      - name: Test nlopt and casadi
        shell: bash -l {0}
        run: |
          micromamba create -y -n test python=${{ matrix.python-version }}
          micromamba activate test
          pip install nlopt casadi
          python -v -c "from nlopt import *; from casadi import *"